python ./DeepLab/train.py ^
    --dataset My ^
    --num_classes 6 ^
    --data_root "./" ^
    --data_dir "1945" ^
    --save_root "./" ^
    --save_dir "models/deeplab/my/" ^
    --log_root "./" ^
    --log_dir "tensorboard" ^
    --lr "1e-4" ^
    --image_width 512 ^
    --image_height 512 ^
    --optimizer "Adam" ^
    --log_visual ^
    --model Deeplab ^
    --backbone Mobilenet ^
    --pretrain_model_path "./models/deeplab/my/best_epoch_weights.pth" ^
    --downsample_factor 16 ^
    --init_epoch 0 ^
    --freeze_epoch 25 ^
    --freeze_batch_size 8 ^
    --unfreeze_epoch 50 ^
    --unfreeze_batch_size 8 ^
    --min_lr 5e-7 ^
    --momentum 0.9 ^
    --weight_decay 0 ^
    --lr_decay_type cos ^
    --focal_loss ^
    --class_weights 1 1 4 4 8 1
